name: Build & Release

on:
  push:
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write

env:
  APP_NAME: core-registry-dashboard

jobs:
  build_web:
    name: Build Core Registry Dashboard Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node 20.10
        uses: actions/setup-node@v4
        with:
          node-version: '20.10'

      - name: Install Husky
        run: npm install --save-dev husky

      - name: npm install and build
        run: |
          node --version
          npm install
          npm run web-build

      - name: Create .tar.gz of the web build
        run: tar -cvzf ${{ env.APP_NAME }}-web-build.tar.gz build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-web-build
          path: ${{ env.APP_NAME }}-web-build.tar.gz

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build_web
    steps:
      - name: Download Web artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-web-build
          path: ${{ env.APP_NAME }}-web-build

      - name: Get Filenames
        run: |
          WEB_FILE=$(find ${{ github.workspace }}/${{ env.APP_NAME }}-web-build/ -type f -name '*.tar.gz')

          echo "WEB_FILE=$WEB_FILE" >>$GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2.0.9
        with:
          files: |
            ${{ env.WEB_FILE }}
